
spring:
  application:
    name: server-provider
  profiles: provider1
server:
  port: 8001
eureka:
  instance:
    hostname: discovery1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/
---

spring:
  application:
    name: server-provider
  profiles: provider2
server:
  port: 8002
eureka:
  instance:
    hostname: discovery2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/
